
    services:
      localhost_db:
        image: "mysql:8"
        restart: always
        ports:
          - 3309:3306
        environment:
          MYSQL_USER: root
          MYSQL_PASSWORD: root
          MYSQL_ROOT_PASSWORD: root
          MYSQL_ROOT_HOST: '%'
          MYSQL_DATABASE: kimu



      spring-demo-app:
        image: spring-demo-image
        build:
          context: .
        restart: always
        ports:
          - 9090:9090
        depends_on:
          - localhost_db
        environment:
              SPRING_DATASOURCE_URL: jdbc:mysql://localhost_db:3306/kimu